version: '3.8'

services:
  directus:
    image: directus/directus:latest
    container_name: directus_app
    restart: always
    ports:
      - "8055:8055"
    environment:
      KEY: "directus-key"
      SECRET: "directus-secret" 

      # Используем SQLite
      DATABASE_CLIENT: "sqlite3"
      DATABASE_FILENAME: "database.sqlite"

      ADMIN_EMAIL: "admin@admin.com"
      ADMIN_PASSWORD: "admin123"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "http://localhost:5173,http://192.168.47.1:5173"

    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
